---
# tasks file for lighthouse
- name: Enable EPEL Repository on CentOS 7
  ansible.builtin.yum:
    name: epel-release
    state: latest
- name: Lighthouse | Install git    
  ansible.builtin.yum:
    name: git
    state: present
- name: Lighhouse | Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present
- name: Lighthouse | Apply nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0644

- name: Lighthouse | Clone repository
  ansible.builtin.git:
    repo: "{{ lighthouse_url }}"
    dest: "{{ lighthouse_dir }}"
    version: master
- name: Lighthouse | Apply config
  become: true
  ansible.builtin.template:
    src: lighthouse_nginx.conf.j2
    dest: /etc/nginx/conf.d/lighthouse.conf
    mode: 0644
  notify: Nginx reload